# Generated by Django 5.2.15 on 2026-07-12 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projectmedia_youtube'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='serviceprojectpin',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='serviceprojectpin',
            name='project',
        ),
        migrations.RemoveField(
            model_name='project',
            name='location',
        ),
        migrations.AddField(
            model_name='project',
            name='main_video',
            field=models.FileField(blank=True, null=True, upload_to='projects/main_videos/'),
        ),
        migrations.AddField(
            model_name='project',
            name='main_video_type',
            field=models.CharField(choices=[('none', 'None'), ('video', 'Uploaded Video'), ('youtube', 'YouTube Video')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='project',
            name='main_video_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.DeleteModel(
            name='HomepageSlot',
        ),
        migrations.DeleteModel(
            name='ServiceProjectPin',
        ),
    ]
