# Generated by Django 5.2.15 on 2026-07-12 22:56

from django.db import migrations, models


def migrate_statuses(apps, schema_editor):
    """Map old single status to the new status/work_status pair.

    Old: draft / in_progress / completed / archived
    New: status (draft/published) + work_status (started/in_progress/completed)
    """
    Project = apps.get_model('projects', 'Project')
    Project.objects.filter(status='completed').update(status='published', work_status='completed')
    Project.objects.filter(status='in_progress').update(status='draft', work_status='in_progress')
    Project.objects.filter(status='archived').update(status='draft', work_status='started')


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_serviceprojectpin_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='work_status',
            field=models.CharField(choices=[('started', 'Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='started', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20),
        ),
        migrations.RunPython(migrate_statuses, migrations.RunPython.noop),
    ]
