"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.0.1.
"""

from pathlib import Path
from datetime import timedelta
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-(s@2kjw9c72^yzovh2gb-3*9-+zm@bmsyuj2nyw0xhyhl(vu^9')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

ALLOWED_HOSTS = [
    'localhost', '127.0.0.1', 'tolatiles.com', 'www.tolatiles.com', 'api.tolatiles.com',
    'quotes.tolatiles.com', 'quote.tolatiles.com',
    '.tolatiles.com',  # leading-dot wildcard: covers admin-created landing page subdomains too
    'backend',  # Docker Compose service DNS name — frontend's server-side fetches hit this directly
]

# Trust X-Forwarded-Proto header from nginx proxy for HTTPS detection
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third party apps
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'django_filters',
    'django_celery_beat',
    'channels',
    'storages',
    # Local apps
    'gallery',
    'leads',
    'authentication',
    'quotes',
    'integrations',
    'notifications',
    'blog',
    'projects',
    'faqs',
    'landingpages',
]

MIDDLEWARE = [
    'django.middleware.gzip.GZipMiddleware',  # GZIP compression - must be first
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Static file serving
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
ASGI_APPLICATION = 'config.asgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# Parse DATABASE_URL if available, otherwise fall back to SQLite
DATABASE_URL = os.environ.get('DATABASE_URL')

if DATABASE_URL:
    # Parse postgres://user:password@host:port/dbname
    import re
    match = re.match(r'postgres://([^:]+):([^@]+)@([^:]+):(\d+)/(.+)', DATABASE_URL)
    if match:
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.postgresql',
                'USER': match.group(1),
                'PASSWORD': match.group(2),
                'HOST': match.group(3),
                'PORT': match.group(4),
                'NAME': match.group(5),
            }
        }
    else:
        raise ValueError(f"Invalid DATABASE_URL format: {DATABASE_URL}")
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/New_York'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (Uploaded images)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Ensure uploaded files/dirs are world-readable so nginx (www-data) can serve
# them. Without this, Django's default umask produces 0640/0750 owned by the
# container user, and nginx returns 403 for /media/ assets (e.g. blog images).
FILE_UPLOAD_PERMISSIONS = 0o644
FILE_UPLOAD_DIRECTORY_PERMISSIONS = 0o755

# --- Blog media storage: local disk by default, Cloudflare R2 in production ---
# Scoped to the blog app only (see blog/storage.py) -- gallery/projects/etc.
# keep using local disk regardless of these settings. Set all four R2_* vars
# to switch blog media (AI-generated images, web-sourced images, inline
# content images, the featured image) over to R2; leave any of them unset
# and blog media keeps behaving exactly as it always has, no R2 account
# required to run this app locally.
R2_BUCKET_NAME = os.environ.get('R2_BUCKET_NAME', '')
R2_ACCOUNT_ID = os.environ.get('R2_ACCOUNT_ID', '')
R2_ACCESS_KEY_ID = os.environ.get('R2_ACCESS_KEY_ID', '')
R2_SECRET_ACCESS_KEY = os.environ.get('R2_SECRET_ACCESS_KEY', '')
# The public URL the bucket is reachable at -- a Cloudflare-dashboard custom
# domain mapped to the bucket (recommended, e.g. "https://media.tolatiles.com"),
# not the private R2 API endpoint below. No trailing slash.
R2_PUBLIC_URL = os.environ.get('R2_PUBLIC_URL', '').rstrip('/')

USE_R2_STORAGE = bool(R2_BUCKET_NAME and R2_ACCOUNT_ID and R2_ACCESS_KEY_ID and R2_SECRET_ACCESS_KEY and R2_PUBLIC_URL)

R2_ENDPOINT_URL = f'https://{R2_ACCOUNT_ID}.r2.cloudflarestorage.com' if R2_ACCOUNT_ID else ''
R2_CUSTOM_DOMAIN = R2_PUBLIC_URL.replace('https://', '').replace('http://', '')

# Single source of truth for "does this URL point at a file our blog media
# storage hosts" (see blog/storage.py::blog_media_key_from_url) -- deliberately
# not derived by probing the storage backend at request time.
MEDIA_PUBLIC_URL_PREFIX = f'{R2_PUBLIC_URL}/' if USE_R2_STORAGE else MEDIA_URL

# --- Financial document storage: local disk by default, private Cloudflare R2
# bucket in production (see quotes/storage.py) ---
# Scoped to the quotes app only (quote/invoice/receipt/estimate PDFs) -- every
# other app is unaffected. Unlike blog media, this bucket is deliberately kept
# PRIVATE (no custom domain, no public access): these are customer financial
# documents, so URLs are short-lived signed S3 URLs generated on request
# rather than permanent public links. Same Cloudflare account as blog media
# (R2_ACCOUNT_ID above), separate bucket and separate scoped credentials.
R2_FINANCIAL_BUCKET_NAME = os.environ.get('R2_FINANCIAL_BUCKET_NAME', '')
R2_FINANCIAL_ACCESS_KEY_ID = os.environ.get('R2_FINANCIAL_ACCESS_KEY_ID', '')
R2_FINANCIAL_SECRET_ACCESS_KEY = os.environ.get('R2_FINANCIAL_SECRET_ACCESS_KEY', '')

USE_R2_FINANCIAL_STORAGE = bool(
    R2_FINANCIAL_BUCKET_NAME and R2_ACCOUNT_ID
    and R2_FINANCIAL_ACCESS_KEY_ID and R2_FINANCIAL_SECRET_ACCESS_KEY
)

# Reuses R2_ENDPOINT_URL above (same account) -- only meaningful when
# USE_R2_FINANCIAL_STORAGE is True.
# How long a signed PDF/receipt URL stays valid once generated, in seconds.
# Long enough that an emailed link or an open browser tab doesn't die on you
# mid-read, short enough that a leaked link doesn't stay live indefinitely.
R2_FINANCIAL_URL_EXPIRE_SECONDS = int(os.environ.get('R2_FINANCIAL_URL_EXPIRE_SECONDS', 60 * 60 * 24))  # 24h

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Django REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'authentication.backends.OptionalJWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
}


# Simple JWT settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': 'HS256',
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
}


# CORS settings
CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',
    'http://127.0.0.1:3000',
    'https://tolatiles.com',
    'https://www.tolatiles.com',
    'https://quotes.tolatiles.com',
    'https://quote.tolatiles.com',
]

# Landing pages are created ad hoc from the admin (new subdomain = new DB row, no deploy),
# so their origins can't be enumerated in the static list above. The frontend always calls
# the API at the fixed https://tolatiles.com/api origin (see NEXT_PUBLIC_API_URL), so a
# browser request from e.g. bathroom.tolatiles.com to tolatiles.com/api is cross-origin and
# needs this regex to get an Access-Control-Allow-Origin header — independent of ALLOWED_HOSTS.
CORS_ALLOWED_ORIGIN_REGEXES = [
    r'^https://([\w-]+\.)?tolatiles\.com$',
]

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]


# Cache Configuration
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'tolatiles-cache',
        'TIMEOUT': 300,  # 5 minutes default
        'OPTIONS': {
            'MAX_ENTRIES': 1000,
        },
    }
}

# Cache timeouts for different resources
CACHE_TTL_CATEGORIES = 60 * 10  # 10 minutes
CACHE_TTL_GALLERY = 60 * 5  # 5 minutes


# Celery Configuration
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes

# Celery Beat Schedule (periodic tasks)
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# Default beat schedule (can be overridden in database)
from celery.schedules import crontab
CELERY_BEAT_SCHEDULE = {
    'publish-scheduled-blog-posts': {
        'task': 'blog.tasks.publish_scheduled_posts',
        'schedule': crontab(minute='*/5'),  # Every 5 minutes
    },
}


# WhiteNoise settings for static files
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# Image processing settings
IMAGE_WEBP_QUALITY = 85
IMAGE_MAX_SIZE = (1920, 1920)  # Max dimensions for gallery images


# Email Configuration
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.mail.us-east-1.awsapps.com"
EMAIL_PORT = 465
EMAIL_USE_SSL = True
EMAIL_USE_TLS = False
EMAIL_HOST_USER = "menitola@tolatiles.com"
EMAIL_HOST_PASSWORD = os.environ.get('WORKMAIL_PASS', '')
DEFAULT_FROM_EMAIL = "Meni Tola <menitola@tolatiles.com>"
SERVER_EMAIL = DEFAULT_FROM_EMAIL


# Frontend URL for redirects
FRONTEND_URL = os.environ.get('FRONTEND_URL', 'https://tolatiles.com')

# Public origin for media URLs returned by the API. Server-side fetches from the
# Next.js frontend hit this backend directly at http://backend:8000 (see 'backend'
# in ALLOWED_HOSTS above), bypassing nginx to dodge its public rate limiter. If we
# let request.build_absolute_uri() run in that case, it stamps the internal Docker
# hostname into image URLs served to the browser, which can't resolve it.
PUBLIC_MEDIA_BASE_URL = os.environ.get('PUBLIC_MEDIA_BASE_URL', 'https://tolatiles.com')


# Google OAuth Settings (Search Console)
GOOGLE_CLIENT_ID = os.environ.get('GOOGLE_CLIENT_ID', '')
GOOGLE_CLIENT_SECRET = os.environ.get('GOOGLE_CLIENT_SECRET', '')

# Google Ads / Local Services Ads Settings
GOOGLE_ADS_DEVELOPER_TOKEN = os.environ.get('GOOGLE_ADS_DEVELOPER_TOKEN', '')
GOOGLE_ADS_LOGIN_CUSTOMER_ID = os.environ.get('GOOGLE_ADS_LOGIN_CUSTOMER_ID', '')
GOOGLE_ADS_CUSTOMER_ID = os.environ.get('GOOGLE_ADS_CUSTOMER_ID', '')
GOOGLE_ADS_CLIENT_ID = os.environ.get('GOOGLE_ADS_CLIENT_ID', '')
GOOGLE_ADS_CLIENT_SECRET = os.environ.get('GOOGLE_ADS_CLIENT_SECRET', '')

# Meta Conversions API (server-side event tracking for landing pages)
META_CAPI_ACCESS_TOKEN = os.environ.get('CAPI_ACCESS_TOKEN', '')
# Temporary while verifying in Meta's Test Events tool; remove this default once confirmed.
# `or` (not .get's default) because docker-compose's ${VAR} substitution sets an empty
# string rather than leaving the key absent when the host has no such env var.
META_CAPI_TEST_EVENT_CODE = os.environ.get('CAPI_TEST_EVENT_CODE') or 'TEST9416'


# Django Channels Configuration
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [(os.environ.get('REDIS_HOST', 'localhost'), 6379)],
        },
    },
}


# Web Push (VAPID) Configuration
VAPID_PUBLIC_KEY = os.environ.get('VAPID_PUBLIC_KEY', '')
VAPID_PRIVATE_KEY = os.environ.get('VAPID_PRIVATE_KEY', '')
VAPID_CLAIMS_EMAIL = os.environ.get('VAPID_CLAIMS_EMAIL', 'menitola@tolatiles.com')


# Gemini AI Configuration
GEMINI_API_KEY = os.environ.get('GEMINI_API_KEY', '')
GEMINI_IMAGE_API_KEY = os.environ.get('GEMINI_IMAGE_API_KEY', '')

# No stock-photo/web-search API keys here by design -- "web" media
# candidates are found via an agent/session with real web access (Claude
# searching + vetting), then downloaded and saved locally via
# blog/services/web_image_service.py. Never a live paid search API call.

