# Generated by Django 5.2.10 on 2026-01-16 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleSearchConsoleCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_refresh_token', models.TextField(blank=True, db_column='refresh_token', null=True)),
                ('_access_token', models.TextField(blank=True, db_column='access_token', null=True)),
                ('token_expiry', models.DateTimeField(blank=True, null=True)),
                ('scope', models.CharField(default='https://www.googleapis.com/auth/webmasters.readonly', max_length=500)),
                ('is_connected', models.BooleanField(default=False)),
                ('connected_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='search_console_credential', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Google Search Console Credential',
                'verbose_name_plural': 'Google Search Console Credentials',
            },
        ),
    ]
