# Generated by Django 5.2.10 on 2026-01-17 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
        ('quotes', '0002_add_timeline_and_service_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalAdsLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_lead_id', models.CharField(help_text='Unique lead ID from Google LSA', max_length=255, unique=True)),
                ('customer_phone', models.CharField(max_length=50)),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('job_type', models.CharField(help_text='Type of job/service requested', max_length=200)),
                ('location', models.CharField(blank=True, help_text='Customer location/address', max_length=500)),
                ('lead_type', models.CharField(choices=[('phone', 'Phone Call'), ('message', 'Message')], max_length=20)),
                ('charge_status', models.CharField(choices=[('charged', 'Charged'), ('not_charged', 'Not Charged')], default='not_charged', max_length=20)),
                ('lead_received', models.DateTimeField(help_text='When the lead was received from Google')),
                ('last_activity', models.DateTimeField(help_text='Last activity timestamp from Google')),
                ('message', models.TextField(blank=True, help_text='Message content if lead type is message')),
                ('call_duration', models.PositiveIntegerField(blank=True, help_text='Call duration in seconds if lead type is phone', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional data from Google LSA API')),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('closed', 'Closed')], default='new', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this lead')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, help_text='Customer created from this lead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='local_ads_leads', to='quotes.customer')),
            ],
            options={
                'verbose_name': 'Local Ads Lead',
                'verbose_name_plural': 'Local Ads Leads',
                'ordering': ['-lead_received'],
                'indexes': [models.Index(fields=['status'], name='leads_local_status_b05b53_idx'), models.Index(fields=['charge_status'], name='leads_local_charge__7d1eed_idx'), models.Index(fields=['lead_received'], name='leads_local_lead_re_67f21a_idx'), models.Index(fields=['google_lead_id'], name='leads_local_google__112e4b_idx')],
            },
        ),
    ]
