# Generated by Django 5.2.10 on 2026-03-07 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_contactlead_contact_result_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactlead',
            name='address',
            field=models.TextField(blank=True, help_text='Customer address (added by admin after contact)'),
        ),
    ]
