# Generated by Django 5.2.15 on 2026-07-02 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpages', '0001_initial'),
        ('leads', '0004_contactlead_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactlead',
            name='landing_page',
            field=models.ForeignKey(blank=True, help_text='Set automatically when the lead was submitted from a landing page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='landingpages.landingpage'),
        ),
        migrations.AddField(
            model_name='contactlead',
            name='lead_source',
            field=models.CharField(blank=True, help_text='Free-text source tag, e.g. "Landing Page: Bathroom Remodel". Set server-side.', max_length=100),
        ),
        migrations.AlterField(
            model_name='contactlead',
            name='email',
            field=models.EmailField(blank=True, help_text='Optional — landing page lead forms may omit this', max_length=254),
        ),
        migrations.AlterField(
            model_name='contactlead',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
