# Generated by Django 5.2.15 on 2026-07-16 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_contactlead_landing_page_contactlead_lead_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactlead',
            name='project_type',
            field=models.CharField(choices=[('kitchen-backsplash', 'Kitchen Backsplash'), ('bathroom', 'Bathroom Tiles'), ('flooring', 'Flooring'), ('patio', 'Patio/Outdoor'), ('fireplace', 'Fireplace'), ('shower', 'Shower Installation'), ('commercial', 'Commercial Project'), ('other', 'Other')], max_length=50),
        ),
    ]
