# Generated by Django 5.2.10 on 2026-01-20 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('new_leads_website', models.PositiveIntegerField(default=0)),
                ('new_leads_local_ads', models.PositiveIntegerField(default=0)),
                ('leads_contacted', models.PositiveIntegerField(default=0)),
                ('leads_converted', models.PositiveIntegerField(default=0)),
                ('quotes_created', models.PositiveIntegerField(default=0)),
                ('quotes_sent', models.PositiveIntegerField(default=0)),
                ('quotes_accepted', models.PositiveIntegerField(default=0)),
                ('quotes_total_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('invoices_created', models.PositiveIntegerField(default=0)),
                ('invoices_paid', models.PositiveIntegerField(default=0)),
                ('invoices_paid_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Daily Stats',
                'verbose_name_plural': 'Daily Stats',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_lead_enabled', models.BooleanField(default=True)),
                ('lead_status_enabled', models.BooleanField(default=True)),
                ('quote_status_enabled', models.BooleanField(default=True)),
                ('invoice_paid_enabled', models.BooleanField(default=True)),
                ('system_enabled', models.BooleanField(default=True)),
                ('push_enabled', models.BooleanField(default=True)),
                ('sound_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('new_lead', 'New Lead'), ('lead_status', 'Lead Status Change'), ('quote_status', 'Quote Status Change'), ('invoice_paid', 'Invoice Paid'), ('system', 'System Notification')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High')], default='normal', max_length=20)),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_via_websocket', models.BooleanField(default=False)),
                ('delivered_via_push', models.BooleanField(default=False)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_object_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx'), models.Index(fields=['user', 'created_at'], name='notificatio_user_id_c62b26_idx'), models.Index(fields=['type'], name='notificatio_type_ea918f_idx')],
            },
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(max_length=500, unique=True)),
                ('p256dh_key', models.CharField(max_length=200)),
                ('auth_key', models.CharField(max_length=100)),
                ('device_name', models.CharField(blank=True, max_length=100)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Push Subscription',
                'verbose_name_plural': 'Push Subscriptions',
                'indexes': [models.Index(fields=['user', 'is_active'], name='notificatio_user_id_1159a5_idx')],
            },
        ),
    ]
