# Generated by Django 5.2.15 on 2026-07-02 20:47

import django.db.models.deletion
import landingpages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Internal label, e.g. "Bathroom Remodel - Meta Ads"', max_length=200)),
                ('subdomain', models.SlugField(help_text='e.g. "bathroom" -> bathroom.tolatiles.com', max_length=63, unique=True, validators=[landingpages.models.validate_subdomain_label])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('page_title', models.CharField(help_text='<title> tag content', max_length=200)),
                ('meta_title', models.CharField(blank=True, help_text='SEO title (max 60 chars). Falls back to page_title if empty.', max_length=60)),
                ('meta_description', models.CharField(blank=True, help_text='SEO description (max 160 chars).', max_length=160)),
                ('canonical_url', models.URLField(blank=True)),
                ('is_indexed', models.BooleanField(default=False, help_text='Allow search engines to index this page (default off — ad landing pages are typically noindex)')),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='landingpages/og/')),
                ('meta_pixel_id', models.CharField(blank=True, help_text='Meta (Facebook) Pixel ID', max_length=30)),
                ('gtm_container_id', models.CharField(blank=True, help_text='Google Tag Manager container ID', max_length=20)),
                ('ga_measurement_id', models.CharField(blank=True, help_text='Google Analytics measurement ID', max_length=20)),
                ('custom_head_scripts', models.TextField(blank=True, help_text='Raw <script> HTML injected into <head>. Admin-trust-level input — executes as-is.')),
                ('custom_body_scripts', models.TextField(blank=True, help_text='Raw <script> HTML injected before </body>. Admin-trust-level input — executes as-is.')),
                ('phone_number', models.CharField(blank=True, help_text='Click-to-call target shared across sections, e.g. +19048661738', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Landing Page',
                'verbose_name_plural': 'Landing Pages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LandingPageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('hero', 'Hero'), ('headline', 'Headline'), ('cta', 'Call to Action'), ('lead_form', 'Lead Form'), ('reviews', 'Reviews'), ('gallery', 'Gallery')], max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_enabled', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Shape depends on section_type, e.g. hero: {headline, subheadline, media_type, image, video_url}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('landing_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='landingpages.landingpage')),
            ],
            options={
                'verbose_name': 'Landing Page Section',
                'verbose_name_plural': 'Landing Page Sections',
                'ordering': ['order'],
                'indexes': [models.Index(fields=['landing_page', 'order'], name='landingpage_landing_23c1f0_idx')],
            },
        ),
    ]
