# Generated by Django 5.2.15 on 2026-07-03 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpagesection',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Shape depends on section_type, e.g. hero: {headline, subheadline, media_type, image, video_url}; custom_code: {html} — raw HTML/CSS/JS, admin-trust-level input'),
        ),
        migrations.AlterField(
            model_name='landingpagesection',
            name='section_type',
            field=models.CharField(choices=[('hero', 'Hero'), ('headline', 'Headline'), ('cta', 'Call to Action'), ('lead_form', 'Lead Form'), ('reviews', 'Reviews'), ('gallery', 'Gallery'), ('custom_code', 'Custom Code')], max_length=20),
        ),
    ]
