# Generated by Django 5.2.10 on 2026-01-24 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blog Category',
                'verbose_name_plural': 'Blog Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('content', models.TextField(help_text='HTML content')),
                ('excerpt', models.TextField(blank=True, help_text='Short summary for listings and meta description fallback', max_length=300)),
                ('author_name', models.CharField(default='Tola Tiles Team', help_text='Display name for the author', max_length=100)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog/featured/')),
                ('featured_image_alt', models.CharField(blank=True, help_text='Alt text for the featured image', max_length=200)),
                ('meta_title', models.CharField(blank=True, help_text='SEO title (max 60 chars). Falls back to title if empty.', max_length=60)),
                ('meta_description', models.CharField(blank=True, help_text='SEO description (max 160 chars). Falls back to excerpt if empty.', max_length=160)),
                ('canonical_url', models.URLField(blank=True, help_text='Canonical URL if different from default')),
                ('is_indexed', models.BooleanField(default=True, help_text='Allow search engines to index this post')),
                ('has_faq_schema', models.BooleanField(default=False, help_text='Enable FAQ schema markup')),
                ('faq_data', models.JSONField(blank=True, default=list, help_text='FAQ data as JSON array: [{"question": "...", "answer": "..."}]')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('scheduled', 'Scheduled')], default='draft', max_length=20)),
                ('publish_date', models.DateTimeField(blank=True, help_text='Date when post was/will be published', null=True)),
                ('scheduled_publish_date', models.DateTimeField(blank=True, help_text='Scheduled date for auto-publishing', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='posts', to='blog.blogcategory')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-publish_date', '-created_at'],
            },
        ),
    ]
