# Generated by Django 5.2.10 on 2026-02-06 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='location',
            field=models.CharField(choices=[('florida', 'Florida'), ('jacksonville', 'Jacksonville'), ('st-augustine', 'St. Augustine')], default='florida', help_text='Target location for this blog post', max_length=20),
        ),
    ]
