# Generated by Django 5.2.15 on 2026-07-13 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='content_type',
            field=models.CharField(choices=[('blog', 'Blog'), ('guide', 'Guide'), ('design_idea', 'Design Idea'), ('story', 'Story')], db_index=True, default='blog', help_text='Which site section this post belongs to', max_length=20),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='related_link_auto_appended',
            field=models.BooleanField(default=False, help_text='Set automatically when publishing appended a CTA link to Related Service Page because the body did not already link to it. Flagged here for editorial review.'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='related_service_page',
            field=models.CharField(blank=True, choices=[('Jacksonville', [('/jacksonville', 'Jacksonville — City Hub'), ('/jacksonville/services/kitchen-backsplash', 'Jacksonville — Kitchen Backsplash'), ('/jacksonville/services/bathroom-tile', 'Jacksonville — Bathroom Tile'), ('/jacksonville/services/floor-tile', 'Jacksonville — Floor Tile'), ('/jacksonville/services/patio-tile', 'Jacksonville — Patio Tile'), ('/jacksonville/services/fireplace-tile', 'Jacksonville — Fireplace Tile'), ('/jacksonville/services/shower-tile', 'Jacksonville — Shower Tile')]), ('St. Augustine', [('/st-augustine', 'St. Augustine — City Hub'), ('/st-augustine/services/kitchen-backsplash', 'St. Augustine — Kitchen Backsplash'), ('/st-augustine/services/bathroom-tile', 'St. Augustine — Bathroom Tile'), ('/st-augustine/services/floor-tile', 'St. Augustine — Floor Tile'), ('/st-augustine/services/patio-tile', 'St. Augustine — Patio Tile'), ('/st-augustine/services/fireplace-tile', 'St. Augustine — Fireplace Tile'), ('/st-augustine/services/shower-tile', 'St. Augustine — Shower Tile')])], default='', help_text='Internal city/service page this post should support. Required to publish Blog posts.', max_length=100),
        ),
    ]
