# Generated by Django 5.2.16 on 2026-07-27 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogpost_media_plan_suggested_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='related_service_page',
            field=models.CharField(blank=True, choices=[('Jacksonville', [('/jacksonville', 'Jacksonville — City Hub'), ('/jacksonville/services/kitchen-backsplash-installation', 'Jacksonville — Kitchen Backsplash'), ('/jacksonville/services/bathroom-tile-installation', 'Jacksonville — Bathroom Tile'), ('/jacksonville/services/floor-tile-installation', 'Jacksonville — Floor Tile'), ('/jacksonville/services/patio-tile-installation', 'Jacksonville — Patio Tile'), ('/jacksonville/services/fireplace-tile-installation', 'Jacksonville — Fireplace Tile'), ('/jacksonville/services/shower-tile-installation', 'Jacksonville — Shower Tile')]), ('St. Augustine', [('/st-augustine', 'St. Augustine — City Hub'), ('/st-augustine/services/kitchen-backsplash-installation', 'St. Augustine — Kitchen Backsplash'), ('/st-augustine/services/bathroom-tile-installation', 'St. Augustine — Bathroom Tile'), ('/st-augustine/services/floor-tile-installation', 'St. Augustine — Floor Tile'), ('/st-augustine/services/patio-tile-installation', 'St. Augustine — Patio Tile'), ('/st-augustine/services/fireplace-tile-installation', 'St. Augustine — Fireplace Tile'), ('/st-augustine/services/shower-tile-installation', 'St. Augustine — Shower Tile')])], default='', help_text='Internal city/service page this post should support. Required to publish Blog posts.', max_length=100),
        ),
    ]
