# Generated by Django 5.2.16 on 2026-08-01 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blogpost_related_service_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='featured_image_plan',
            field=models.JSONField(blank=True, default=dict, help_text='Featured image candidate plan: {"prompt", "status", "resolved_source", "resolved_url", "candidates": {"ai", "gallery", "web"}}. status is "unresolved" | "resolved" | "skipped".', null=True),
        ),
    ]
