# Generated by Django 5.0.1 on 2026-01-10 23:35

import django.db.models.deletion
import quotes.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(help_text='Name of the person sending quotes', max_length=100)),
                ('title', models.CharField(blank=True, help_text='Job title (e.g., Sales Representative)', max_length=100)),
                ('email', models.EmailField(help_text='Contact email for quotes', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=20)),
                ('company_name', models.CharField(help_text='Company name', max_length=200)),
                ('company_address', models.TextField(help_text='Full company address')),
                ('company_logo', models.ImageField(blank=True, help_text='Company logo for PDFs', null=True, upload_to='company/')),
            ],
            options={
                'verbose_name': 'Company Settings',
                'verbose_name_plural': 'Company Settings',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Customer name or company name', max_length=200)),
                ('phone', models.CharField(help_text='Primary phone number', max_length=20)),
                ('email', models.EmailField(blank=True, help_text='Email address for sending quotes', max_length=254)),
                ('address', models.TextField(blank=True, help_text='Full address')),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this customer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default=quotes.models.generate_invoice_reference, editable=False, help_text='Auto-generated invoice reference', max_length=20, unique=True)),
                ('title', models.CharField(help_text='Invoice title / project name', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('due_date', models.DateField(help_text='Payment due date')),
                ('paid_at', models.DateTimeField(blank=True, help_text='Date payment received', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='draft', max_length=20)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro')], default='USD', max_length=3)),
                ('notes', models.TextField(blank=True, help_text='Additional notes for customer')),
                ('payment_terms', models.TextField(blank=True, help_text='Payment terms and instructions')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('shipping_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount already paid', max_digits=12)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='invoices/')),
                ('pdf_generated_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='quotes.customer')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Item/service name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='quotes.invoice')),
            ],
            options={
                'verbose_name': 'Invoice Line Item',
                'verbose_name_plural': 'Invoice Line Items',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default=quotes.models.generate_quote_reference, editable=False, help_text='Auto-generated quote reference', max_length=20, unique=True)),
                ('title', models.CharField(help_text='Quote title / project name', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateField(help_text='Quote expiration date')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('expired', 'Expired')], default='draft', max_length=20)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro')], default='USD', max_length=3)),
                ('comments_text', models.TextField(blank=True, help_text='Scope of work / comments section (supports multiple paragraphs)')),
                ('terms', models.JSONField(blank=True, default=list, help_text='Array of purchase terms (strings)')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Fixed discount amount', max_digits=12)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentage discount (0-100)', max_digits=5)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tax rate percentage (0-100)', max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('shipping_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Shipping/delivery cost', max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='quotes/')),
                ('pdf_generated_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(help_text='Customer for this quote', on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='quotes.customer')),
            ],
            options={
                'verbose_name': 'Quote',
                'verbose_name_plural': 'Quotes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Item/service name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Quantity', max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit', max_digits=12)),
                ('detail_lines', models.JSONField(blank=True, default=list, help_text='Array of sub-detail strings (shown as smaller text below item)')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='quotes.quote')),
            ],
            options={
                'verbose_name': 'Line Item',
                'verbose_name_plural': 'Line Items',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='quote',
            field=models.ForeignKey(blank=True, help_text='Original quote if created from one', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='quotes.quote'),
        ),
    ]
