# Generated by Django 5.0.1 on 2026-01-11 01:30

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitem',
            name='is_service',
            field=models.BooleanField(default=False, help_text='If True, this is a service (no quantity shown, uses flat price)'),
        ),
        migrations.AddField(
            model_name='quote',
            name='timeline',
            field=models.CharField(blank=True, default='2-3 weeks', help_text='Project timeline (e.g., "2-3 weeks", "1 month")', max_length=100),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Quantity (ignored if is_service is True)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, help_text='Price per unit (or flat price for services)', max_digits=12),
        ),
    ]
