# Generated by Django 5.2.10 on 2026-03-07 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_estimate_deal_estimatelineitem_estimatephoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='estimate',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='quote',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='title',
        ),
        migrations.AddField(
            model_name='deal',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='estimated_sqft',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='job_type',
            field=models.CharField(blank=True, choices=[('kitchen_backsplash', 'Kitchen Backsplash'), ('bathroom', 'Bathroom'), ('flooring', 'Flooring'), ('patio', 'Patio'), ('fireplace', 'Fireplace'), ('commercial', 'Commercial'), ('other', 'Other')], max_length=30),
        ),
        migrations.AddField(
            model_name='deal',
            name='lead_source',
            field=models.CharField(blank=True, choices=[('website', 'Website'), ('referral', 'Referral'), ('google_ads', 'Google Ads'), ('walk_in', 'Walk-in'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='quotes.deal'),
        ),
        migrations.AddField(
            model_name='quote',
            name='deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='quotes.deal'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='stage',
            field=models.CharField(choices=[('new_deal', 'New Deal'), ('estimate_scheduled', 'Estimate Scheduled'), ('quote_sent', 'Quote Sent'), ('invoice_sent', 'Invoice Sent'), ('won', 'Won'), ('lost', 'Lost')], default='new_deal', max_length=30),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('scheduled_date', models.DateTimeField()),
                ('appointment_type', models.CharField(choices=[('consultation', 'Consultation'), ('follow_up', 'Follow-up'), ('measurement', 'Measurement'), ('other', 'Other')], default='consultation', max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='quotes.deal')),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'ordering': ['scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='EstimateVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('scheduled_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimate_visits', to='quotes.deal')),
            ],
            options={
                'verbose_name': 'Estimate Visit',
                'verbose_name_plural': 'Estimate Visits',
                'ordering': ['scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='EstimateVisitPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='estimate_visits/photos/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='quotes.estimatevisit')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
