# Generated by Django 5.2.10 on 2026-03-13 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0006_customer_archived_at_customer_is_archived_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='customers/photos/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='quotes.customer')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
