# Generated by Django 5.2.10 on 2026-05-31 01:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0011_finalize_installment_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sum of paid installments (auto-calculated)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentage discount 0-100 (used when discount_type=percent)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='invoiceinstallment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Fixed discount amount (used when discount_type=fixed)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='quote',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentage discount 0-100 (used when discount_type=percent)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='quote',
            name='discount_type',
            field=models.CharField(choices=[('percent', 'Percentage'), ('fixed', 'Fixed Amount')], default='percent', help_text='Whether discount is a percentage or fixed amount', max_length=10),
        ),
    ]
