# Generated by Django 5.2.10 on 2026-05-31 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0012_alter_invoice_amount_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='payment_terms',
            field=models.TextField(blank=True, help_text='Pricing notes / payment terms shown to customer on the PDF'),
        ),
    ]
