# Generated by Django 5.2.15 on 2026-06-24 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0014_quote_portal_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='portal_contact_name',
            field=models.CharField(blank=True, default='', help_text='Name entered by the portal user (not linked to a Customer record)', max_length=200),
        ),
    ]
